// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU_wyuRbv_d6O-HxSOctJpXAzoVsfScb8',
    appId: '1:653336945048:web:aee8a2fc67e8fb57ec8bed',
    messagingSenderId: '653336945048',
    projectId: 'ecosortai-ce598',
    authDomain: 'ecosortai-ce598.firebaseapp.com',
    storageBucket: 'ecosortai-ce598.firebasestorage.app',
    measurementId: 'G-PJEKFR0J7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDleZf_56YYxnMu6AB3hme4GbEM-Vg3aUE',
    appId: '1:653336945048:android:2ce0d206ac2b7275ec8bed',
    messagingSenderId: '653336945048',
    projectId: 'ecosortai-ce598',
    storageBucket: 'ecosortai-ce598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHT5WnCN9ZxIR1RvDOfOwwdv0pqi8ne1c',
    appId: '1:653336945048:ios:29beabff1b6a2ef3ec8bed',
    messagingSenderId: '653336945048',
    projectId: 'ecosortai-ce598',
    storageBucket: 'ecosortai-ce598.firebasestorage.app',
    iosBundleId: 'com.example.ecoSortAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHT5WnCN9ZxIR1RvDOfOwwdv0pqi8ne1c',
    appId: '1:653336945048:ios:29beabff1b6a2ef3ec8bed',
    messagingSenderId: '653336945048',
    projectId: 'ecosortai-ce598',
    storageBucket: 'ecosortai-ce598.firebasestorage.app',
    iosBundleId: 'com.example.ecoSortAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU_wyuRbv_d6O-HxSOctJpXAzoVsfScb8',
    appId: '1:653336945048:web:9a82fa2fc9405054ec8bed',
    messagingSenderId: '653336945048',
    projectId: 'ecosortai-ce598',
    authDomain: 'ecosortai-ce598.firebaseapp.com',
    storageBucket: 'ecosortai-ce598.firebasestorage.app',
    measurementId: 'G-64BMLWX00V',
  );
}
